// <auto-generated />
using Andrade_LigaPro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Andrade_LigaPro.Migrations
{
    [DbContext(typeof(Andrade_LigaProContext))]
    partial class Andrade_LigaProContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Andrade_LigaPro.Models.equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("partidosEmpatados")
                        .HasColumnType("int");

                    b.Property<int>("partidosGanados")
                        .HasColumnType("int");

                    b.Property<int>("partidosJugados")
                        .HasColumnType("int");

                    b.Property<int>("partidosPerdidos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("equipo");
                });
#pragma warning restore 612, 618
        }
    }
}
